apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot
  namespace: ai-chatbot
spec:
  selector:
    app: ai-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
